### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by pawelkontek** [hxf31891/react-gradient-color-picker#5]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/7879784/177030497-a701dec5-4766-4a27-8506-f1a20ac3a10a.png">
The elements are not responsive, but rather have fixed width.

**Comment by hxf31891** [comment]
When I first build the component, it had a fixed width (294 px). I've been looking into changing this and instead having a picker width prop passed in.

Will push to the top of the list and keep you updated.

**Comment by dmbarry86** [comment]
@hxf31891 did you make any progress with this? We require this responsiveness for one of our tools so I would be happy to help out if you didn't manage to do it yet.

**Comment by dmbarry86** [comment]
Just to follow up, we would like to achieve something like this.

![image](https://user-images.githubusercontent.com/8976377/186111251-889cb7dc-cff3-424d-9306-ee25e5b81ff0.png)

I think this would mean changing the [Square](https://github.com/hxf31891/react-gradient-color-picker/blob/main/src/Square.js) component to support width and height. At the moment I see there is a `squareSize` defined in the [constants](https://github.com/hxf31891/react-gradient-color-picker/blob/5d78753b75d59b79942475cd5ead146ca76d6cfa/src/constants.js#L2) file. I guess this needs to be replaced by width and height props instead (with defaults still 294). Side note, it seems like this constant is not referenced everywhere, e.g. the square component itself seems to have hardcoded 294px rather than referencing the constant.

**Comment by hxf31891** [comment]
@dmbarry86 apologies for the delay, I believe this issue to be fixed with version 2.0.11. You can now pass in the prop width.
I am closing this issue but please feel free to raise issues with this or other issues that you find. Appreciate the contribution!

**Comment by dmbarry86** [comment]
Thanks @hxf31891 I'll check it out. I only see 2.0.8 in the [releases](https://github.com/hxf31891/react-gradient-color-picker/releases) though. Am I missing something?

**Comment by hxf31891** [comment]
Updating GH release now!

@pawelkontek see `[1227046015](https://github.com/hxf31891/react-gradient-color-picker/issues/5#issuecomment-1227046015)`

**Comment by dmbarry86** [comment]
Sorry one other question @hxf31891 . To achieve the design I showed in the screenshot above I think we would also need to specify height as well as width. Is height prop also available or could it be added?

**Comment by hxf31891** [comment]
@dmbarry86 ahhh I'm better understanding your desired design now. 

I don't believe that introducing a height prop will be particularly challenging. Will update you ASAP.
